### ISSUE TITLE
Use the LPPL

### ISSUE THREAD

**Issue by vermiculus** [qTipTip/TM-style-class#1]
From [Reddit](https://www.reddit.com/r/LaTeX/comments/3zudx3/working_on_a_modern_documentclass_for_latex_what/cyq4em9?context=10000):

Don't use the GPL!! [The infectious GPL is not safe to use for LaTeX code.](https://latex-project.org/papers/tb100mittbach-lppl-history.pdf) It would require that all derivative works and products be licensed under the GPL which is _simply not feasible_ for the vast majority of authors. Additionally, all products will need the _complete_ source code distributed with it – this technically includes the author's work, your work, the work that you based your work on (mdframed), all the way down the rabbit hole to XeLaTeX's source code which, by the way, is not GPL.

Use the [LaTeX Project Public License](https://latex-project.org/lppl/) and keep your work open source while allowing your users to to freely distribute the product without restriction.

**Comment by qTipTip** [comment]
Thanks! I saw the Reddit post - i am not well versed in the world of
licences, but wiser everyday!

Fixed now :)
8. jan. 2016 03.18 skrev "Sean Allred" notifications@github.com:

**Comment by HarveySheppard** [comment]
Hi vermiculus and qTipTip,
I really thank you for bringing this problem up to me. I changed the licence but I'm not totally convinced. GPL might not suit LaTeX work but the LPPL allows to make commercial use of the work which is something I don't want.

As I'm neither very good with licenses, _I was wondering if you knew one that would prevent commercial use._

**Comment by qTipTip** [comment]
Hmm - what about the Creative Commons licences for non-commercial use? I've just read up on them:
Maybe one of these two? There are more to be found here: https://creativecommons.org/licenses/

## Attribution-NonCommercial

### CC BY-NC

This license lets others remix, tweak, and build upon your work non-commercially, and although their new works must also acknowledge you and be non-commercial, they don’t have to license their derivative works on the same terms.

## Attribution-NonCommercial-ShareAlike

### CC BY-NC-SA

This license lets others remix, tweak, and build upon your work non-commercially, as long as they credit you and license their new creations under the identical terms.

**Comment by vermiculus** [comment]
Disclaimer: I am not a lawyer, etc.

That's the problem: commercial use needs to be allowed to a certain extent. What would not be allowed (as I understand it) is commercial distribution of your source code.

LaTeX is a bit weird in that there are two distinct works: the TeX source file (which can be split up into many files) and the compiled output (which is (edit: usually) one file). The compiled output needs to be sellable, but the source file -- perhaps even your source file -- can (and should) remain free in all senses.

See also http://tex.stackexchange.com/a/82719/17423. The LPPL is a free software license, but most writers don't write for free. Even journal publication would be prohibited with an inappropriate license (like CC/GPL).

**Comment by vermiculus** [comment]
See also [`texdoc modguide`](http://texdoc.net/texmf-dist/doc/latex/base/modguide.pdf).

**Comment by vermiculus** [comment]
Why has this been closed?

**Comment by vermiculus** [comment]
Oh! It looks like the license changed in 7f43fd6eee057f0e34531ac3ff754a6f5cef50d3. Thanks!
